# Generated by Django 3.1.3 on 2022-07-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
