# Generated by Django 3.1.3 on 2022-07-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20220730_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/button.png', upload_to='media/'),
        ),
    ]
