# Generated by Django 3.1.3 on 2022-07-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyw', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Post',
        ),
    ]
