# Generated by Django 3.1.3 on 2022-07-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyw', '0002_auto_20220721_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='Post',
        ),
    ]
