# Generated by Django 3.1.3 on 2022-07-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyw', '0003_auto_20220721_0050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posting',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='Posting',
        ),
    ]
