# Generated by Django 3.1.3 on 2022-07-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyw', '0007_auto_20220723_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='auhor',
            new_name='author',
        ),
    ]
