# Generated by Django 3.1.3 on 2022-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyw', '0015_auto_20220723_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='board_name',
            field=models.CharField(default='백엔드', max_length=32, verbose_name='게시판 종류'),
        ),
    ]
