# Generated by Django 3.1.3 on 2022-07-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyw', '0016_posting_board_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('has_comment', models.BooleanField(default=True)),
            ],
        ),
    ]
