# Generated by Django 3.1.3 on 2022-07-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wyw', '0017_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='board_name',
        ),
        migrations.AddField(
            model_name='posting',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_posting', to='wyw.category'),
            preserve_default=False,
        ),
    ]
