# Generated by Django 3.1.3 on 2022-07-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wyw', '0019_auto_20220723_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_queston', to='wyw.category'),
        ),
    ]
