# Generated by Django 3.1.3 on 2022-07-28 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wyw', '0021_auto_20220723_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='scrap_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posting',
            name='scraper',
            field=models.ManyToManyField(related_name='scrap_posting', to=settings.AUTH_USER_MODEL),
        ),
    ]
