# Generated by Django 3.1.3 on 2022-08-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyw', '0023_posting_author_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posting',
            name='user_Rating',
            field=models.FloatField(default=0),
        ),
    ]
