# Generated by Django 3.2.14 on 2022-08-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyw', '0024_auto_20220805_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='logo',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
