# Generated by Django 3.2.14 on 2022-08-13 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wyw', '0025_posting_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='logo',
        ),
    ]
