# Generated by Django 3.2.14 on 2022-08-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyw', '0026_remove_posting_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='user_Rating',
        ),
        migrations.AddField(
            model_name='posting',
            name='logo',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
